name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # SDK Version Strategy:
  # Use semver patterns: ^7.0.0 (latest 7.x), ^8.0.0 (latest 8.x), or exact version: 8.3.0
  # Note: "latest" is NOT supported by the CLI tool
  # See docs/SDK_SETUP.md for details
  # Updated to match local development environment (SDK 8.3.0)
  CONNECTIQ_SDK_VERSION: "^8.0.0"

jobs:
  build-and-test:
    # Use latest Ubuntu - CLI SDK Manager doesn't need GUI libs!
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Cache Connect IQ SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/connectiq-sdk
            ~/.Garmin/ConnectIQ/Sdks
            ~/.Garmin/ConnectIQ/Devices
          # Include SDK version in cache key so different versions use different caches
          # v4: Added devices directory to cache
          key: connectiq-sdk-${{ runner.os }}-${{ env.CONNECTIQ_SDK_VERSION }}-v4
          restore-keys: |
            connectiq-sdk-${{ runner.os }}-${{ env.CONNECTIQ_SDK_VERSION }}-
            connectiq-sdk-${{ runner.os }}-
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          # CLI SDK Manager only needs basic tools - no GUI libraries!
          sudo apt-get install -y shellcheck wget unzip
      
      - name: Setup Developer Key
        env:
          MONKEYC_KEY_B64: ${{ secrets.MONKEYC_KEY_B64 }}
        run: |
          # Use env var instead of direct secret interpolation (more secure)
          mkdir -p .keys
          echo "$MONKEYC_KEY_B64" | base64 -d > .keys/developer_key.der
      
      - name: Setup Connect IQ SDK
        env:
          # Pass credentials directly to this step only (more secure)
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: |
          if [ ! -d ~/connectiq-sdk/bin ]; then
            echo "Setting up Connect IQ SDK $CONNECTIQ_SDK_VERSION..."
            ./scripts/setup_sdk.sh
          else
            echo "✓ SDK cached ($(~/connectiq-sdk/bin/monkeyc --version 2>&1 | head -n1))"
            
            # Verify devices exist, download if missing
            if [ ! -d ~/.Garmin/ConnectIQ/Devices/fr265 ]; then
              echo "Downloading devices..."
              
              # Install CLI SDK Manager
              curl -s https://raw.githubusercontent.com/lindell/connect-iq-sdk-manager-cli/master/install.sh | sh -s -- -b /tmp >/dev/null 2>&1
              
              # Login (required for device downloads)
              /tmp/connect-iq-sdk-manager login --username="$GARMIN_USERNAME" --password="$GARMIN_PASSWORD" >/dev/null 2>&1 || true
              
              # Download devices
              if ! /tmp/connect-iq-sdk-manager device download --device fr265 --device fenix7 --device epix2 --device venu2; then
                echo "Warning: Bulk download failed, trying individually..."
                for device in fr265 fenix7 epix2 venu2; do
                  /tmp/connect-iq-sdk-manager device download --device "$device" || echo "Failed: $device"
                done
              fi
              echo "✓ Devices downloaded"
            else
              echo "✓ Devices cached (4 devices available)"
            fi
          fi
          
          echo "$HOME/connectiq-sdk/bin" >> $GITHUB_PATH
          echo "SDK_HOME=$HOME/connectiq-sdk" >> $GITHUB_ENV
      
      - name: Verify Devices Installed
        run: |
          echo "Checking for required devices..."
          DEVICES_DIR="$HOME/.Garmin/ConnectIQ/Devices"
          
          if [ ! -d "$DEVICES_DIR" ]; then
            echo "ERROR: Devices directory not found at $DEVICES_DIR"
            exit 1
          fi
          
          for device in fr265 fenix7 epix2 venu2; do
            if [ -d "$DEVICES_DIR/$device" ]; then
              echo "✓ $device"
            else
              echo "✗ $device MISSING"
              exit 1
            fi
          done
          
          echo "All devices verified!"
      
      - name: Validate Environment
        run: |
          echo "Validating build environment..."
          make validate
          make version
      
      - name: Build All Devices
        run: make buildall -j4 DEBUG_LOG=1
      
      - name: List Build Artifacts
        run: |
          echo "Build artifacts:"
          ls -lh bin/*.prg
      
      # Tests require simulator GUI - skip in CI for now
      # To enable: setup xvfb-run or use headless simulator setup
      # - name: Run Tests
      #   run: xvfb-run -a make test
      
      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          retention-days: 30
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prg-files
          path: bin/*.prg
          retention-days: 90
