name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Use Ubuntu 22.04 for webkit2gtk-4.0 compatibility with SDK Manager
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Cache Connect IQ SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/connectiq-sdk
            ~/.Garmin/ConnectIQ/Sdks
          key: connectiq-sdk-manager-${{ runner.os }}-v2
          restore-keys: |
            connectiq-sdk-manager-${{ runner.os }}-
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          # SDK Manager requires webkit2gtk-4.0 which is available in Ubuntu 22.04
          sudo apt-get install -y xvfb shellcheck wget unzip libsecret-1-0 libwebkit2gtk-4.0-37 libgtk-3-0
      
      - name: Setup Developer Key
        run: |
          mkdir -p .keys
          echo "${{ secrets.MONKEYC_KEY_B64 }}" | base64 -d > .keys/developer_key.der
      
      - name: Setup Connect IQ SDK
        run: |
          # Uses official SDK Manager to download and install SDK
          # SDK Manager downloads the latest compatible SDK version
          # Cache speeds up subsequent runs significantly
          if [ ! -d ~/connectiq-sdk/bin ]; then
            echo "SDK not cached, running SDK Manager installation..."
            ./scripts/setup_sdk.sh
          else
            echo "SDK found in cache, skipping installation"
          fi
          echo "$HOME/connectiq-sdk/bin" >> $GITHUB_PATH
          echo "SDK_HOME=$HOME/connectiq-sdk" >> $GITHUB_ENV
      
      - name: Validate Environment
        run: |
          make validate
          make devices
          make version
      
      - name: Build All Devices
        run: make buildall -j4
      
      - name: List Build Artifacts
        run: |
          echo "Build artifacts:"
          ls -lh bin/*.prg
      
      # Tests require simulator GUI - skip in CI for now
      # To enable: setup xvfb-run or use headless simulator setup
      # - name: Run Tests
      #   run: xvfb-run -a make test
      
      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          retention-days: 30
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prg-files
          path: bin/*.prg
          retention-days: 90
